version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: teste_prova_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: teste_prova_bd
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: teste_prova_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/teste_prova_bd
      SPRING_DATASOURCE_USER: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"


volumes:
  db_data: